language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: S6iPqck1fiu5S48lxJStcWgN/DAESHZuoUs2WDX+H0JOuhTbnQ6MYMaulTvmbm0Tiq+EQaNZAGq7o4EtGKJ0TtGAM/u4CLx0LWBC1ubOy17siBe+vNJLJGxr1U0Mq2F8aU6xUMHq9h9gaT2adcncw1SD1iwVmgOUmMn6pIiiy9EP9a2/jd3U7eibRFrOkVl5oNKzZx3BegFCfX6EXsqsYusmWqHhheKrrRUSdDhT6yJ4YIe6OQ6oH7nuUDDrPHxVxfIHsyQPaU7ZSOCN40VPyNfRUp3VyefVppclUfcZblqwxkpw989/LXNu1rmnBpFI87RFV/X3lb5/uCXmQg/m3sb0KC5E9VzV+SKPEIeW0vQXwMUvXpOL99z5gOaMogwZt2vHrQzfWqfLnj4lfh2ZwvZAL2b3+DSZmg41H7qWRE09ANVjv+HWIi7QlScRsdfSs1gah9tmNXtN9pd2JwA/2KlLA1IDVF2mn55VRQ96JWKjMipL2X4mTcV9cVDQ2JzN2cTkrPpirn3VD59iB5AMgbz+d/+J/7xoN9IQuDl9h5BAx8+U2yiKRA/Ae9LZObEgjwFFxokYnyw7liTpdCozRRrre9yHOgzJ4u6JhV/HYNizTud1hkZkZ7GCutm0iqYB0qKnnIwlN69FXEUKsYXtVYzmu739J5sftuXlcRDWEL8=
  on:
    tags: true
    repo: mrossi93/med_dataloader
    python: 3.8
