language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: ljWsMadsCGBCPafQd3AnlPvRkI3YrNwj1bxW8hOAKBpw67Bk5Hb3sttDQMA/+204x7BnnOzBidshFGZUNreXyFIMFDpwnv+EtBJkSHhXpkH81szCEmjXOkioQPiuj25K0nrSQWJulhdtxeDyeQl0MEuKDcEmwM50U0AMQAJFfDETMRrfV4nU49Kk0r4v9I+/zqwuon7gv3TR3DSZa4mRqS+xrs4+8sfztzSyiEIaw2rygF1tzRxeLwLgwAjeW71EhQmswze9wwuGh5oLMmyNOKetzZC82S0GINqQ+oduP4lPQskWpUWb4Lj0z+LW4OYaZPhmNWKYbD89fVrVqk1n+Qf42AuABHSP9Mr8GmuX5HW8NUV1qZElexPPOYgjvLz0y8OLSWLehPagmD4jpv6NbBpnUySQqwxMnMQFXDhrwM9SWvgDYayvyrK0/z6H1RjYxi/8DaIIlugDeaVgpUFjbF90iaUeKJwdfBSrcDJlifjNOJzkZ0llp2cT8X16d8OJvKjNpDqwPugXS0KEsqyndwYxtnb+1WW+gC+0I6+SVcrNBRzXnXemhf5RYYDgl/Oxo3dIuBGt/hbgaSl2WjylRMbGDVoEfFo7v4fr2Qba7Rg736AdRegfJrK9O2LG6DGsR13fXqv5o0SqaulBepmsWzBDZuh9oYATUQMHaf+6e3U=
  on:
    tags: true
    repo: mrossi93/med_dataloader
    python: 3.8
